"use client";
import { useState } from "react";

type Assistant={name:string;identity:string;tone:string;colors:string};
type Message={from:"user"|"assistant";text:string};
const assistants:Assistant[]=[
  {name:"Avery",identity:"Woman",tone:"Warm & focused",colors:"avatar-coral"},
  {name:"Jordan",identity:"Man",tone:"Calm & capable",colors:"avatar-blue"},
  {name:"Sage",identity:"Nonbinary",tone:"Bright & direct",colors:"avatar-gold"},
  {name:"Maya",identity:"Woman",tone:"Polished & kind",colors:"avatar-violet"},
  {name:"Elliot",identity:"Man",tone:"Friendly & precise",colors:"avatar-green"}
];
const samples=["Call Dr. Chen and find an appointment next week","Pay the electric bill Friday","Text Hannah: Lunch changed to 1:15 PM"];
function PersonIcon(){return <svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="29" r="14" fill="currentColor" opacity=".92"/><path d="M14 73c2-18 12-28 26-28s24 10 26 28" fill="currentColor" opacity=".92"/></svg>}
function Spark(){return <span aria-hidden="true" className="spark">✦</span>}

export default function Home(){
  const [introduced,setIntroduced]=useState(false);
  const [selected,setSelected]=useState<number|null>(null);
  const [started,setStarted]=useState(false);
  const [chores,setChores]=useState<string[]>([]);
  const [draft,setDraft]=useState("");
  const [chatTask,setChatTask]=useState<number|null>(null);
  const [chatDraft,setChatDraft]=useState("");
  const [messages,setMessages]=useState<Message[]>([]);
  const [pricing,setPricing]=useState(false);
  const assistant=assistants[selected??0];

  if(pricing)return <main className="pricing-shell"><nav className="topbar dashboard-nav"><button className="back-button" onClick={()=>setPricing(false)}>← Back</button><a className="brand" href="#"><span className="brand-mark"><Spark/></span>PERSECT</a><span className="nav-tag">PLANS</span></nav><section className="pricing-page"><header><p className="eyebrow-left"><Spark/> CHOOSE YOUR TIME BACK</p><h1>A plan for every kind of day.</h1><p>Start free. Buy chores as you need them, or let PERSECT handle your day every day.</p></header><div className="pricing-grid"><article className="price-card"><span className="plan-number">01</span><h2>Try PERSECT</h2><p className="price"><strong>Free</strong><small>for 1 week</small></p><p className="plan-copy">Experience your personal secretary before choosing a plan.</p><ul><li>One active chore at a time</li><li>Chat for changes and hiccups</li><li>Confirmation before action</li></ul><button>Start free week</button><div className="token-box"><span>THEN BUY TOKENS AS NEEDED</span><div><button>$5</button><button>$10</button><button>$20</button></div></div></article><article className="price-card"><span className="plan-number">02</span><h2>PERSECT Monthly</h2><p className="price"><strong>$19.95</strong><small>per month</small></p><p className="plan-copy">Reliable help for everyday appointments, calls, messages, and chores.</p><ul><li>One active chore at a time</li><li>Ongoing PERSECT Chat</li><li>Monthly recurring access</li></ul><button>Choose Monthly</button></article><article className="price-card featured"><span className="popular">BEST VALUE</span><span className="plan-number">03</span><h2>PERSECT Four</h2><p className="price"><strong>$49.95</strong><small>per month</small></p><p className="annual">or <b>$495 annually</b> — save $104.40</p><p className="plan-copy">Create chores all day and keep four moving at the same time.</p><ul><li>Four active chore squares</li><li>Unlimited daily use</li><li>Create new chores all day</li><li>Priority handling and chat</li></ul><button>Choose PERSECT Four</button></article><article className="price-card family"><span className="family-badge">UP TO 6 MEMBERS</span><span className="plan-number">04</span><h2>PERSECT Family</h2><p className="price"><strong>$95</strong><small>per month</small></p><p className="plan-copy">Premium PERSECT access for the whole household.</p><ul><li>Up to six individual members</li><li>Premium package for every member</li><li>Four active chore squares each</li><li>Upgrade or downgrade anytime</li></ul><button>Choose Family</button></article></div><p className="billing-note">PERSECT subscription charges do not include bills, purchases, appointment fees, or third-party service charges. You approve sensitive actions before they happen.</p></section></main>;

  const addChore=(value=draft)=>{const clean=value.trim();if(!clean||chores.length>=4)return;setChores([...chores,clean]);setDraft("")};
  const openChat=(index:number|null)=>{
    setChatTask(index);
    const subject=index===null?"your day":chores[index];
    setMessages([{from:"assistant",text:`I’m here. Tell me what changed, ask a question, or let me know where you hit a dead end with ${subject}.`}]);
  };
  const sendMessage=()=>{
    const clean=chatDraft.trim();if(!clean)return;
    const updated=[...messages,{from:"user" as const,text:clean}];
    const timeChange=/\b(change|move|instead|reschedule|later|earlier|time)\b/i.test(clean);
    const reply=timeChange
      ?"Got it. I’ll treat this as an update to your original prompt. I’ll use the new time and ask you to confirm before I notify anyone."
      :"Thanks for flagging that. I’ll pause the task, work around the hiccup, and check with you before making a different choice.";
    setMessages([...updated,{from:"assistant",text:reply}]);setChatDraft("");
  };

  if(!introduced)return <main className="landing-shell"><nav className="topbar landing-nav"><a className="brand" href="#"><span className="brand-mark"><Spark/></span>PERSECT</a><button className="pricing-link" onClick={()=>setPricing(true)}>Plans & pricing</button></nav><section className="landing-hero"><div className="landing-copy"><p className="eyebrow-left"><Spark/> YOUR DAY, HANDLED</p><h1>What took up<br/><em>half your day</em></h1><p className="hero-answer">your PERSECT can do with a<br/><strong>5-minute prompt.</strong></p><button className="hero-button" onClick={()=>setIntroduced(true)}>Choose your PERSECT <span>→</span></button><p className="hero-note">Delegate appointments, calls, messages and everyday chores.</p></div><div className="time-card"><div className="clock"><span className="clock-center"/><span className="clock-hand hour"/><span className="clock-hand minute"/></div><div className="time-saved"><span>TIME SAVED</span><strong>½ DAY</strong></div><div className="prompt-chip"><Spark/><span><b>One prompt</b><small>PERSECT handles the rest</small></span><strong>5 min</strong></div></div></section><section className="saved-question"><span>THE QUESTION IS</span><h2>What will you do with<br/><em>all the time you save?</em></h2></section></main>;

  if(!started)return <main className="onboarding-shell"><nav className="topbar"><a className="brand" href="#"><span className="brand-mark"><Spark/></span>PERSECT</a><span className="step-label">STEP 1 OF 2</span></nav><section className="onboarding"><div className="eyebrow"><span/> MAKE IT YOURS <span/></div><h1>Choose your <em>PERSECT.</em></h1><p className="intro">Pick the personal secretary you&apos;ll be working with.<br/>You can change this anytime.</p><div className="profiles" role="radiogroup" aria-label="Choose your personal secretary">{assistants.map((a,i)=><button key={a.name} type="button" role="radio" aria-checked={selected===i} className={`profile-card ${selected===i?"selected":""}`} onClick={()=>setSelected(i)}><span className={`avatar ${a.colors}`}><PersonIcon/></span><span className="profile-name">{a.name}</span><span className="identity">{a.identity}</span><span className="tone">{a.tone}</span><span className="check">✓</span></button>)}</div><button className="continue" disabled={selected===null} onClick={()=>setStarted(true)}>Continue with {selected===null?"your secretary":assistants[selected].name} <span>→</span></button><p className="privacy">Your preferences stay private and can be updated in Settings.</p></section></main>;

  if(chatTask!==null||messages.length>0)return <main className="chat-shell"><nav className="topbar dashboard-nav"><button className="back-button" onClick={()=>{setChatTask(null);setMessages([])}}>← Four squares</button><a className="brand" href="#"><span className="brand-mark"><Spark/></span>PERSECT</a><button className={`mini-avatar ${assistant.colors}`}><PersonIcon/></button></nav><section className="chat-page"><header className="chat-header"><p className="eyebrow-left"><Spark/> TALK IT THROUGH</p><h1>Chat with {assistant.name}</h1><p>Questions, hiccups, dead ends, or a change from your original prompt.</p>{chatTask!==null&&<div className="original-prompt"><span>ORIGINAL PROMPT</span><strong>{chores[chatTask]}</strong></div>}</header><div className="conversation" aria-live="polite">{messages.map((m,i)=><div key={i} className={`message ${m.from}`}>{m.from==="assistant"&&<span className={`message-avatar ${assistant.colors}`}><PersonIcon/></span>}<div><small>{m.from==="assistant"?assistant.name:"You"}</small><p>{m.text}</p></div></div>)}</div><div className="chat-suggestions"><button onClick={()=>setChatDraft("Change the time from 1:00 PM to 1:15 PM")}>Change the time</button><button onClick={()=>setChatDraft("I hit a dead end. What are my options?")}>Report a dead end</button><button onClick={()=>setChatDraft("Ask me before choosing another option")}>Change instructions</button></div><div className="chat-composer"><textarea value={chatDraft} onChange={e=>setChatDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder={`Message ${assistant.name}…`}/><button onClick={sendMessage} disabled={!chatDraft.trim()}>Send ↑</button></div><p className="chat-safety">Changes to messages, appointments, or payments require your confirmation.</p></section></main>;

  return <main className="workspace-shell"><nav className="topbar dashboard-nav"><a className="brand" href="#"><span className="brand-mark"><Spark/></span>PERSECT</a><div className="nav-actions"><button className="chat-nav" onClick={()=>openChat(null)}>Chat</button><span className="plan-pill">PERSECT FOUR</span><button className={`mini-avatar ${assistant.colors}`} onClick={()=>setStarted(false)} aria-label="Change secretary"><PersonIcon/></button></div></nav><section className="workspace"><div className="greeting"><p className="eyebrow-left"><Spark/> YOUR DAY, HANDLED</p><h1>What can I handle<br/>for you today?</h1><p>{assistant.name} is ready. Add up to four chores at a time.</p></div><div className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();addChore()}}} placeholder="Type a chore, appointment, message, or reminder…" aria-label="Add a chore"/><div className="composer-row"><button className="mic" aria-label="Use voice input">●</button><span>{chores.length} of 4 active</span><button className="add-button" onClick={()=>addChore()} disabled={!draft.trim()||chores.length>=4}>Add chore <b>↑</b></button></div></div><div className="quick-row">{samples.map((s,i)=><button key={s} onClick={()=>addChore(s)} disabled={chores.length>=4}><span>{["☎","$","✉"][i]}</span>{s}</button>)}</div><div className="square-heading"><h2>Your four squares</h2><span>{4-chores.length} available</span></div><div className="chore-grid">{[0,1,2,3].map(index=>{const chore=chores[index];return chore?<article className="chore-card active" key={index}><div className="card-top"><span className="number">0{index+1}</span><span className="status">READY TO START</span></div><p>{chore}</p><div className="task-chat-row"><button onClick={()=>openChat(index)}>Chat about this chore →</button></div><div className="card-bottom"><span>{assistant.name} will ask before sensitive actions.</span><button onClick={()=>setChores(chores.filter((_,i)=>i!==index))} aria-label={`Remove ${chore}`}>×</button></div></article>:<button className="chore-card empty" key={index} onClick={()=>document.querySelector<HTMLTextAreaElement>("textarea")?.focus()}><span className="plus">+</span><span>Square {index+1}</span><small>Tap to add a chore</small></button>})}</div></section></main>;
}
